name: MBASE SDK Build
on:
  push:
    branches:
      - devops/test
jobs:
  ubuntu-amd64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      
      - name: Dev dependency install
        run: sudo apt install uuid-dev

      - name: MBASE build
        run: |
          cmake -B build_amd64 -DMBASE_FORCE_BUNDLE=ON -DMBASE_PACKAGING=ON
          cmake --build build_amd64 --config Release -j
          cpack -G "TGZ;ZIP;DEB" --config ./build_amd64/CPackConfig.cmake
          ls

  windows-amd64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: MBASE build
        run: |
          cmake -B build_amd64 -DMBASE_FORCE_BUNDLE=ON -DMBASE_PACKAGING=ON
          cmake --build build_amd64 --config Release -j
          cpack -G "TGZ;ZIP;NSIS" --config ./build_amd64/CPackConfig.cmake
          ls

  macos-metal-build:
    runs-on: macos-13
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: MBASE build
        run: |
          cmake -B build -DMBASE_FORCE_BUNDLE=ON -DMBASE_PACKAGING=ON
          cmake --build build --config Release -j
          cpack -G "TGZ;ZIP" --config ./build/CPackConfig.cmake
          ls