name: MBASE SDK Build
on:
  push:
    branches:
      - devops/test
    
jobs:

  macos-metal-build:
    runs-on: mbase-arm-mac1
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: MBASE build
        run: |
          cmake -B build -DMBASE_FORCE_BUNDLE=ON -DMBASE_PACKAGING=ON
          cmake --build build --config Release -j
          cpack -G "TGZ;ZIP" --config ./build/CPackConfig.cmake
          ls