name: documentation build
on:
  push:
    branches:
      - devops/test
    
jobs:
  doc_build:
    runs-on: mbase-docbuilder-ubuntu
    steps:
      - name: Checkout the documentation branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build sphinx docs
        run: |
          sphinx-build -M html ./docs/source ./docs/build
          ~/docs_update.sh