name: documentation build
on:
  push:
    branches:
      - devops/test
    
jobs:
  macos-metal-build:
    runs-on: macos-13
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: MBASE build
        run: |
          cmake -B build -DMBASE_FORCE_BUNDLE=ON -DMBASE_PACKAGING=ON
          cmake --build build --config Release -j
          rm -rf ./output
          mkdir output
          cd output
          cpack -G "ZIP;TGZ" --config ../build/CPackConfig.cmake
          ls