name: MBASE SDK Release

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  ubuntu-amd64-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      
      - name: System dependency install
        run: |
          sudo apt-get -y install file
          sudo apt-get -y install uuid-dev
          sudo apt-get -y install rpm

      - name: AMD64 bundled build
        run: |
          cmake -B build_amd64_bundle -DMBASE_FORCE_BUNDLE=ON -DMBASE_SERVER_SSL=ON -DMBASE_PACKAGING=ON
          cmake --build build_amd64_bundle --config Release -j
          rm -rf ./output
          mkdir output

      - name: Packaging the program
        run: |
          cd output
          cpack -G "ZIP;TGZ;DEB;RPM" --config ../build_amd64_bundle/CPackConfig.cmake
          rm -rf ./_CPack_Packages
          cd ..
          gh release upload "$(git describe --tags --abbrev=0)" ./output/* --clobber