name: MBASE SDK Release

on:
  workflow_dispatch:

jobs:

  macos-metal-release:
    runs-on: mbase-arm-mac1
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        run: git fetch --prune --unshallow
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      
      - name: Metal bundled build
        run: |
          rm -rf build_metal_bundle
          cmake -B build_metal_bundle -DMBASE_FORCE_BUNDLE=ON -DMBASE_SERVER_SSL=ON -DMBASE_PACKAGING=ON
          cmake --build build_metal_bundle --config Release -j
          rm -rf ./output
          mkdir output
          cd output
          cpack -G "ZIP;TGZ" --config ../build_metal_bundle/CPackConfig.cmake
          rm -rf ./_CPack_Packages
          cd ..
      
      - name: Uploading artifacts
        run: |
          gh release upload "$(git describe --tags --abbrev=0)" ./output/* --clobber